# Generated by Django 5.0.1 on 2024-02-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Todo", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="5",
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
