# Generated by Django 5.0.1 on 2024-02-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Todo", "0003_remove_task_5_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
